name = "mediafire-worker"
type = "javascript"
account_id = "mediafirelinks"
workers_dev = true

[[kv_namespaces]]
binding = "mediafirelinks_KV"
id = "267a8171-d0f4-40dd-b740-d56711d94c07" # Seu Namespace ID
