name = "mediafirelinks"
type = "javascript"
account_id = "3469a0ba-58a7-45f1-b35e-28e89fd53f30"
workers_dev = true

kv_namespaces = [
  { binding = "MEDIAFIRE_KV", id = "3469a0ba-58a7-45f1-b35e-28e89fd53f30" }
]
